APP_NAME = ECX-Backend-Project-1
NODE = node
NPM = npm

build:
	@echo "Building $(APP_NAME)..."
	@$(NPM) install

test:
	@echo "Running Test For All $(APP_NAME) Api Endpoints..."
	@$(NPM) test -- --exit

run:
	@echo "Running $(APP_NAME)..."
	@$(NODE) index.js

clean:
	@echo "Cleaning up..."
	@$(NPM) cache clean

all: build test run clean

.DEFAULT_GOAL := all

.PHONY: build test run clean all
